#cloud-config
## Required syntax at the start of user-data file
users:
## Create the default user for the OS
  - default

  - name: vp
    gecos: victor pupim
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    lock_passwd: false
    shell: /bin/bash
    plain_text_passwd: bekind
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCpp8QTL41ymP8vdfTWOnQ7yxZzNEcU9MiVhH6KpzYhsvDlF7R+5k14rqSjj0eFPk3eVXey/GSKaMR0B/oR2Xcv96cTns3s2vFkokYJizWbdJaSX0Uq/qEZR1fTWkrooLCtsRhKXXAKdj+J999kzMCo1hN081xHyPupyaq+Z2Ut6JsAVtITHq8j+0g3SRwPC9QT2mUBz/t8M8uLzQahz6VvQK8dbDZJBiN6MwQ0OOuVk4TqfqevEzH1mkiYEYKLgkUO/wAFBfceFw+CpIe0RvAhwbonhV85LNrEg31MECNy6m13S1MV6mEEpxjPsDV2DAQjN/wt5x3UXzzP4iKKewexnx+V2ISAlXLOzopOI2Ku50XkbHQFEAM3wG6QJqdBzQVQ04tdIvjSu3VtuMr8faUoOVJWEuip1sc/sZm59OwBA1lDn+ob9H+dtUL8BQdT9S4WvdHRnJGrZzMpALFJDkI5HBNsFpaiZcHwTZXI6G4viZJUaGUcaEitxOkWD1eUvO6XF1RvKMNM8kf7ndPg8ZytLB/mvYJpa+SErOW0Qw1p2MZPHQxmfq987b5XJ2MV4kcItSBlWDz8fBNn4Z1JWgEywHT62f9KuDtxry/a/25/6f34TuWBjxDPUP8lq8ZE+kIN2J1Qi05ASAsdwYfwamoNoY4yjhf9DEhNefcm3hGlhw== pupimvictor@gmail.com
      
    
## Enable DHCP on the default network interface provisioned in the VM
network:
  version: 2
  ethernets:
      ens192:
          dhcp4: true

runcmd:
  - mkdir /home/vp/workspace
  - wget https://10.220.46.34/wcp/plugin/linux-amd64/vsphere-plugin.zip
  - unzip vsphere-plugin.zip
  - mv bin/* /usr/local/bin/
  - tanzu init


# https://vc01.h2o-2-551.h2o.vmware.com:443/cls/vcsp/lib/76c8acf6-5030-4c19-a204-c5b4ce743f2b/lib.json