apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: vm
spec:
  className: best-effort-large
  imageName: ubuntu-20-1633387172196 
  storageClass: vc01cl01-t0compute 
  volumes:
  - name: workspace
    persistentVolumeClaim: 
      claimName: ubuntu-pv
  networkInterfaces:
  - networkName: user-workload
    networkType: vsphere-distributed
  powerState: poweredOn
  vmMetadata:
    configMapName: ubuntu-os-config
    transport: OvfEnv


